# -*- coding: utf-8 -*-
"""api

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkA0m0b4U7uDtAmBotdLEWkB4tXJJ_wU
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Any
from rag_pipeline import load_documents, split_documents, create_rag_chain

documents = load_documents("Руководство по насосам шламовым 4 DY -AHF.pdf")
chunks = split_documents(documents)
rag_chain = create_rag_chain(chunks)

app = FastAPI()


class QueryRequest(BaseModel):
    query: str


@app.post("/ask")
def ask(request: QueryRequest) -> Any:
    try:
        response = rag_chain.invoke({"input": request.query})
        return {"answer": response["answer"]}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))