# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkA0m0b4U7uDtAmBotdLEWkB4tXJJ_wU
"""

import streamlit as st
import requests

st.title("Технический помощник по насосам DY")

query = st.text_input("Введите вопрос:")

if st.button("Задать вопрос") and query.strip():
    with st.spinner("Обработка..."):
        try:
            response = requests.post("http://api:8000/ask", json={"query": query})
            if response.status_code == 200:
                st.markdown(f"**Ответ:**\n\n{response.json()['answer']}")
            else:
                st.error(f"Ошибка: {response.status_code}")
        except Exception as e:
            st.error(f"Ошибка соединения: {e}")